### ISSUE TITLE
Script Cannot Find SVGs

### ISSUE THREAD

**Issue by KikoKlyde** [Mynotaurus/Yingmotes#10]
trying to get a brand colored nom_zatzhing for a project on Windows 10 Powershell with latest python and fresh installs of requirements; had to hand hold it to the generate.py, but doing so with the desired SVG did not work
```
PS C:\Users\**[REDACTED]**> python.exe .\Documents\yingmotes\generate.py palette.kikoklyde ying_nom_zatzhing.svg
-- Finding SVGs...
Traceback (most recent call last):
  File "C:\Users\Riley K\Documents\yingmotes\generate.py", line 13, in <module>
    for entry in os.listdir(basepath):
                 ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: './svg/'
```

**Comment by Mynotaurus** [comment]
ah, you need to run the script from the directory the yingmotes are in. use `cd` to navigate the terminal to the yingmotes root directory (the folder where generate.py is) then it should work by just running `python generate.py [your arguments]`

ill add this info to the readme too, must have forgotten to add it, sorry!
