### ISSUE TITLE
Setting heart colours to #0000 does not hide the heart outline

### ISSUE THREAD

**Issue by Zuthal** [Mynotaurus/Yingmotes#12]
Version used: Yingmotes 4.0 development branch
Expected behaviour: Setting heart_inner and heart_outer to #0000 should completely hide the hearts.
Actual behaviour: Setting heart_inner and heart_outer both to #0000 hides the inside of the heart, but renders the outside in black.
Steps to reproduce: Set heart_inner and heart_outer in a palette to #0000, and generate any yingmote that contains a heart with that palette.

**Comment by Mynotaurus** [comment]
added a fix coming in zhe next update v4.0! https://github.com/Mynotaurus/Yingmotes/commit/53831ddce9396b1fcc04817d7e2bd2718fe2f7a8
